(()=>{'use strict';
const KEY='kreditplaner_v1',$=s=>document.querySelector(s),euro=new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'});
function money(v){const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.round(n*100)/100):0}
function nextFirst(){const d=new Date(),t=new Date(d.getFullYear(),d.getMonth()+1,1);return `${t.getFullYear()}-${String(t.getMonth()+1).padStart(2,'0')}-01`}
function parse(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s||''))return null;const[y,m,d]=s.split('-').map(Number);return {y,m,d}}
function installments(start,end){const a=parse(start),b=parse(end);if(!a||!b)return 0;const diff=(b.y-a.y)*12+(b.m-a.m);if(diff<0)return 0;if(diff===0&&b.d<a.d)return 0;return diff+1}
function uid(){return `${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x&&Array.isArray(x.loans)?x:{loans:[]}}catch{return{loans:[]}}}
function fmtInterest(v){const n=Number(v);return Number.isFinite(n)?`${n.toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:4})} %`:'—'}
function prepare(){
 const modal=$('#loanModal'),save=$('#saveLoan'),end=$('#end');if(!modal||!save||!end)return;
 let row=$('#optionalLoanFields');
 if(!row){row=document.createElement('div');row.id='optionalLoanFields';row.className='row';row.innerHTML='<div class="field"><label for="optStart">Startdatum (optional)</label><input id="optStart" type="date"></div><div class="field"><label for="optInterest">Jahreszins % (optional)</label><input id="optInterest" type="number" min="0" step="0.01" inputmode="decimal" placeholder="z. B. 3,5"></div>';end.closest('.field')?.after(row)}
 const start=$('#optStart'),interest=$('#optInterest');
 new MutationObserver(()=>{if(!modal.classList.contains('on'))return;const id=$('#loanId')?.value||'',state=load(),loan=state.loans.find(l=>l.id===id);start.value=loan?.startDate||'';interest.value=loan?.annualInterest??''}).observe(modal,{attributes:true,attributeFilter:['class']});
 save.onclick=()=>{const id=$('#loanId').value,name=$('#name').value.trim(),rate=money($('#rate').value),endDate=$('#end').value,startDate=start.value||'',annualInterest=interest.value===''?null:Number(interest.value);if(!name||!rate||!endDate)return alert('Bitte Name, Monatsrate und Enddatum ausfüllen.');if(annualInterest!==null&&(!Number.isFinite(annualInterest)||annualInterest<0))return alert('Bitte einen gültigen Jahreszins eingeben.');const state=load();if(id){const l=state.loans.find(x=>x.id===id);if(!l)return;l.name=name;l.rate=rate;l.endDate=endDate;l.startDate=startDate;l.annualInterest=annualInterest}else{const due=nextFirst(),n=installments(due,endDate);if(!n)return alert('Das Enddatum muss am oder nach der nächsten Rate liegen.');const sum=money(rate*n);state.loans.push({id:uid(),name,original:sum,balance:sum,rate,nextDue:due,endDate,startDate,annualInterest,history:[]})}localStorage.setItem(KEY,JSON.stringify(state));location.reload()};
 function decorate(){const state=load();document.querySelectorAll('#loanList .loan').forEach(card=>{if(card.dataset.optionsDone)return;const l=state.loans.find(x=>x.id===card.dataset.id),grid=card.querySelector('.loanGrid');if(!l||!grid)return;if(l.startDate){const x=document.createElement('div');x.className='info';x.innerHTML=`<small>Startdatum</small><strong>${new Intl.DateTimeFormat('de-DE').format(new Date(l.startDate+'T00:00:00'))}</strong>`;grid.appendChild(x)}if(l.annualInterest!==null&&l.annualInterest!==undefined&&l.annualInterest!==''){const x=document.createElement('div');x.className='info';x.innerHTML=`<small>Jahreszins</small><strong>${fmtInterest(l.annualInterest)}</strong>`;grid.appendChild(x)}card.dataset.optionsDone='1'})}
 const list=$('#loanList');if(list){new MutationObserver(decorate).observe(list,{childList:true,subtree:true});decorate()}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(prepare,0));else setTimeout(prepare,0);
})();