(function(){
'use strict';
var PRIVATE_KEY='kreditplaner_v1';
var SHARED_KEY='kreditplaner_shared_code';
var ENDPOINT='https://ymjngslafotilihvvbbl.supabase.co/functions/v1/couple-sync';
var APIKEY='sb_publishable_dLzM2hTl77RvOIEdc78hRA_5xJAF02r';
function q(s){return document.querySelector(s)}
function qa(s){return document.querySelectorAll(s)}
function money(v){var n=Number(v);if(!isFinite(n))n=0;return Math.max(0,Math.round(n*100)/100)}
function load(){try{var x=JSON.parse(localStorage.getItem(PRIVATE_KEY)||'{"loans":[]}');if(x&&Array.isArray(x.loans))return x}catch(e){}return{loans:[]}}
function save(s){localStorage.setItem(PRIVATE_KEY,JSON.stringify(s))}
function uid(){return String(new Date().getTime())+String(Math.random()).slice(2,8)}
function nextFirst(){var d=new Date();return new Date(d.getFullYear(),d.getMonth()+1,1).toISOString().slice(0,10)}
function parseDate(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s||''))return null;var p=s.split('-');return new Date(Date.UTC(Number(p[0]),Number(p[1])-1,Number(p[2])))}
function installments(a,b){var x=parseDate(a),y=parseDate(b);if(!x||!y)return 0;var n=(y.getUTCFullYear()-x.getUTCFullYear())*12+y.getUTCMonth()-x.getUTCMonth();return n<0?0:n+1}
function today(){var d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate()).toISOString().slice(0,10)}
function showPage(id,btn){var ps=qa('.page'),ts=qa('.tab'),i;for(i=0;i<ps.length;i++)ps[i].classList.remove('on');for(i=0;i<ts.length;i++)ts[i].classList.remove('on');var p=document.getElementById(id);if(p)p.classList.add('on');if(btn)btn.classList.add('on');if(id==='shared')renderShared()}
function openLoan(id){var s=load(),l=null,i;if(id){for(i=0;i<s.loans.length;i++)if(String(s.loans[i].id)===String(id)){l=s.loans[i];break}}q('#loanId').value=l?l.id:'';q('#loanTitle').textContent=l?'Kredit bearbeiten':'Kredit anlegen';q('#name').value=l&&l.name?l.name:'';q('#rate').value=l&&l.rate!=null?l.rate:'';q('#end').value=l&&l.endDate?l.endDate:'';q('#start').value=l&&l.startDate?l.startDate:'';q('#interest').value=l&&l.annualInterest!=null?l.annualInterest:'';var del=q('#deleteLoan');if(del)del.style.display=l?'block':'none';q('#loanModal').classList.add('on')}
function closeModal(node){while(node&&node!==document.body&&!node.classList.contains('modal'))node=node.parentNode;if(node&&node.classList.contains('modal'))node.classList.remove('on')}
function saveLoan(){var s=load(),id=q('#loanId').value,name=q('#name').value.trim()||'Kredit',rate=money(q('#rate').value),end=q('#end').value,start=q('#start').value,iv=q('#interest').value,interest=iv===''?null:Number(iv),i,l;if(!rate||!end){alert('Bitte Monatsrate und Enddatum ausfüllen.');return}if(id){for(i=0;i<s.loans.length;i++)if(String(s.loans[i].id)===String(id)){l=s.loans[i];break}if(!l)return;l.name=name;l.rate=rate;l.endDate=end;l.startDate=start;l.annualInterest=interest}else{var due=nextFirst(),n=installments(due,end);if(!n){alert('Enddatum liegt vor der nächsten Rate.');return}var sum=money(rate*n);s.loans.push({id:uid(),name:name,original:sum,balance:sum,rate:rate,nextDue:due,endDate:end,startDate:start,annualInterest:interest,history:[]})}save(s);q('#loanModal').classList.remove('on');location.reload()}
function openBackup(){q('#backupModal').classList.add('on')}
function bind(){var tabs=qa('.tab'),i;for(i=0;i<tabs.length;i++){tabs[i].onclick=function(e){if(e)e.preventDefault();showPage(this.getAttribute('data-page'),this);return false}}var adds=qa('[data-action="add"]');for(i=0;i<adds.length;i++){adds[i].onclick=function(e){if(e)e.preventDefault();openLoan('');return false}}var backs=qa('[data-action="backup"]');for(i=0;i<backs.length;i++){backs[i].onclick=function(e){if(e)e.preventDefault();openBackup();return false}}var closes=qa('[data-close]');for(i=0;i<closes.length;i++){closes[i].onclick=function(e){if(e)e.preventDefault();closeModal(this);return false}}var sl=q('#saveLoan');if(sl)sl.onclick=function(e){if(e)e.preventDefault();saveLoan();return false};var list=q('#loanList');if(list)list.onclick=function(e){e=e||window.event;var t=e.target||e.srcElement,card=t;while(card&&card!==list&&!(card.classList&&card.classList.contains('loan')))card=card.parentNode;if(!card||card===list)return;var id=card.getAttribute('data-id');if(t.hasAttribute('data-edit'))openLoan(id);else if(t.hasAttribute('data-special')){q('#spId').value=id;q('#spAmt').value='';q('#spDate').value=today();q('#specialModal').classList.add('on')}};var ver=q('.version');if(ver)ver.textContent='Kredit App · v28';}
function renderShared(){var root=q('#sharedRoot');if(!root)return;var code=localStorage.getItem(SHARED_KEY)||'';if(!code){root.innerHTML='<div class="card"><h2>Gemeinsam</h2><p class="muted">Noch keine gemeinsame Verbindung eingerichtet.</p></div>';return}root.innerHTML='<div class="card">Gemeinsame Daten werden geladen …</div>';try{var xhr=new XMLHttpRequest();xhr.open('POST',ENDPOINT,true);xhr.setRequestHeader('Content-Type','application/json');xhr.setRequestHeader('apikey',APIKEY);xhr.onreadystatechange=function(){if(xhr.readyState!==4)return;if(xhr.status<200||xhr.status>=300){root.innerHTML='<div class="card"><h2>Gemeinsam</h2><p class="muted">Verbindung konnte nicht geladen werden.</p></div>';return}try{var j=JSON.parse(xhr.responseText),loans=j.loans||[],html='<div class="card"><h2>'+(j.space&&j.space.name?j.space.name:'Gemeinsam')+'</h2><p class="muted">Synchronisierung aktiv</p></div>';if(!loans.length)html+='<div class="empty">Noch kein gemeinsamer Kredit.</div>';for(var k=0;k<loans.length;k++){var l=loans[k];html+='<div class="loan"><div class="loanTop"><div><h3>'+(l.name||'Kredit')+'</h3><div class="loanMeta">Rate '+money(l.rate).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})+' €</div></div><strong>'+money(l.balance).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})+' €</strong></div></div>'}root.innerHTML=html}catch(err){root.innerHTML='<div class="card">Gemeinsame Daten konnten nicht gelesen werden.</div>'}};xhr.send(JSON.stringify({action:'list',code:code}))}catch(e){root.innerHTML='<div class="card">Gemeinsame Daten konnten nicht geladen werden.</div>'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();