(function(){
'use strict';
var PRIVATE_KEY='kreditplaner_v1';
var SHARED_KEY='kreditplaner_shared_code';
var ENDPOINT='https://ymjngslafotilihvvbbl.supabase.co/functions/v1/couple-sync';
var APIKEY='sb_publishable_dLzM2hTl77RvOIEdc78hRA_5xJAF02r';
var sharedLoans=[],sharedTx=[];
function q(s){return document.querySelector(s)}
function qa(s){return document.querySelectorAll(s)}
function money(v){var n=Number(v);if(!isFinite(n))n=0;return Math.max(0,Math.round(n*100)/100)}
function euro(v){return money(v).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})+' €'}
function load(){try{var x=JSON.parse(localStorage.getItem(PRIVATE_KEY)||'{"loans":[]}');if(x&&Array.isArray(x.loans))return x}catch(e){}return{loans:[]}}
function save(s){localStorage.setItem(PRIVATE_KEY,JSON.stringify(s))}
function uid(){return String(new Date().getTime())+String(Math.random()).slice(2,8)}
function nextFirst(){var d=new Date();return new Date(d.getFullYear(),d.getMonth()+1,1).toISOString().slice(0,10)}
function parseDate(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s||''))return null;var p=s.split('-');return new Date(Date.UTC(Number(p[0]),Number(p[1])-1,Number(p[2])))}
function fmt(s){var d=parseDate(s);return d?new Intl.DateTimeFormat('de-DE').format(d):'—'}
function installments(a,b){var x=parseDate(a),y=parseDate(b);if(!x||!y)return 0;var n=(y.getUTCFullYear()-x.getUTCFullYear())*12+y.getUTCMonth()-x.getUTCMonth();return n<0?0:n+1}
function addM(s,n){var d=parseDate(s);if(!d)return null;var day=d.getUTCDate(),t=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+n,1)),last=new Date(Date.UTC(t.getUTCFullYear(),t.getUTCMonth()+1,0)).getUTCDate();t.setUTCDate(Math.min(day,last));return t.toISOString().slice(0,10)}
function projected(balance,rate,due){balance=money(balance);rate=money(rate);if(!balance||!rate||!due)return null;return addM(due,Math.max(0,Math.ceil(balance/rate)-1))}
function today(){var d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate()).toISOString().slice(0,10)}
function api(action,data,cb){var code=localStorage.getItem(SHARED_KEY)||'',xhr=new XMLHttpRequest(),body={action:action,code:code},k;data=data||{};for(k in data)body[k]=data[k];xhr.open('POST',ENDPOINT,true);xhr.setRequestHeader('Content-Type','application/json');xhr.setRequestHeader('apikey',APIKEY);xhr.onreadystatechange=function(){if(xhr.readyState!==4)return;var j={};try{j=JSON.parse(xhr.responseText||'{}')}catch(e){}if(xhr.status<200||xhr.status>=300)return cb(new Error(j.error||'Verbindung fehlgeschlagen'));cb(null,j)};xhr.send(JSON.stringify(body))}
function ensurePrivateStartAmount(){if(q('#startAmount'))return;var details=q('#loanModal details');if(!details)return;var inner=details.querySelector('div');if(!inner)return;var f=document.createElement('div');f.className='field';f.innerHTML='<label>Startbetrag (€)</label><input id="startAmount" type="number" min="0" step="0.01" inputmode="decimal" placeholder="optional">';inner.insertBefore(f,inner.firstChild)}
function showPage(id,btn){var ps=qa('.page'),ts=qa('.tab'),i;for(i=0;i<ps.length;i++)ps[i].classList.remove('on');for(i=0;i<ts.length;i++)ts[i].classList.remove('on');var p=document.getElementById(id);if(p)p.classList.add('on');if(btn)btn.classList.add('on');if(id==='shared')renderShared()}
function findPrivate(id){var s=load(),i;for(i=0;i<s.loans.length;i++)if(String(s.loans[i].id)===String(id))return s.loans[i];return null}
function openLoan(id){ensurePrivateStartAmount();var s=load(),l=null,i;if(id){for(i=0;i<s.loans.length;i++)if(String(s.loans[i].id)===String(id)){l=s.loans[i];break}}q('#loanId').value=l?l.id:'';q('#loanTitle').textContent=l?'Kredit bearbeiten':'Kredit anlegen';q('#name').value=l&&l.name?l.name:'';q('#rate').value=l&&l.rate!=null?l.rate:'';q('#end').value=l&&l.endDate?l.endDate:'';q('#start').value=l&&l.startDate?l.startDate:'';q('#interest').value=l&&l.annualInterest!=null?l.annualInterest:'';if(q('#startAmount'))q('#startAmount').value=l&&l.original!=null?l.original:'';var del=q('#deleteLoan');if(del)del.style.display=l?'block':'none';q('#loanModal').classList.add('on')}
function closeModal(node){while(node&&node!==document.body&&!node.classList.contains('modal'))node=node.parentNode;if(node&&node.classList.contains('modal'))node.classList.remove('on')}
function saveLoan(){ensurePrivateStartAmount();var s=load(),id=q('#loanId').value,name=q('#name').value.trim()||'Kredit',rate=money(q('#rate').value),end=q('#end').value,start=q('#start').value,iv=q('#interest').value,interest=iv===''?null:Number(iv),entered=money(q('#startAmount')?q('#startAmount').value:0),i,l;if(!rate||!end){alert('Bitte Monatsrate und Enddatum ausfüllen.');return}if(id){for(i=0;i<s.loans.length;i++)if(String(s.loans[i].id)===String(id)){l=s.loans[i];break}if(!l)return;l.name=name;l.rate=rate;l.endDate=end;l.startDate=start;l.annualInterest=interest;if(entered>0)l.original=Math.max(entered,money(l.balance));}else{var due=nextFirst(),n=installments(due,end);if(!n){alert('Enddatum liegt vor der nächsten Rate.');return}var sum=money(rate*n),original=entered>0?Math.max(entered,sum):sum;s.loans.push({id:uid(),name:name,original:original,balance:sum,rate:rate,nextDue:due,endDate:end,startDate:start,annualInterest:interest,history:[]})}save(s);q('#loanModal').classList.remove('on');location.reload()}
function openBackup(){q('#backupModal').classList.add('on')}
function sharedModal(title,html){var m=q('#sharedV30Modal');if(!m){m=document.createElement('div');m.id='sharedV30Modal';m.className='modal';m.innerHTML='<div class="sheet"><h3 id="sharedV30Title"></h3><div id="sharedV30Body"></div><button class="btn" id="sharedV30Close" style="width:100%;margin-top:10px">Schließen</button></div>';document.body.appendChild(m);q('#sharedV30Close').onclick=function(){m.classList.remove('on')}}q('#sharedV30Title').textContent=title;q('#sharedV30Body').innerHTML=html;m.classList.add('on');return m}
function openSharedEdit(id){var l=null,i;for(i=0;i<sharedLoans.length;i++)if(String(sharedLoans[i].id)===String(id)){l=sharedLoans[i];break}if(!l)return;var m=sharedModal('Gemeinsamen Kredit bearbeiten','<div class="field"><label>Name</label><input id="seName"></div><div class="field"><label>Monatsrate (€)</label><input id="seRate" type="number" step="0.01"></div><div class="field"><label>Enddatum</label><input id="seEnd" type="date"></div><div class="field"><label>Startdatum (optional)</label><input id="seStart" type="date"></div><div class="field"><label>Jahreszins % (optional)</label><input id="seInterest" type="number" step="0.01"></div><button class="btn primary" id="seSave" style="width:100%">Änderungen speichern</button><button class="btn danger" id="seDelete" style="width:100%;margin-top:10px">Kredit löschen</button>');q('#seName').value=l.name||'';q('#seRate').value=l.rate==null?'':l.rate;q('#seEnd').value=l.end_date||'';q('#seStart').value=l.start_date||'';q('#seInterest').value=l.annual_interest==null?'':l.annual_interest;q('#seSave').onclick=function(){var name=q('#seName').value.trim()||'Kredit',rate=money(q('#seRate').value),end=q('#seEnd').value,st=q('#seStart').value||null,iv=q('#seInterest').value,ai=iv===''?null:Number(iv);if(!rate||!end)return alert('Bitte Monatsrate und Enddatum ausfüllen.');api('update_loan',{loan_id:id,name:name,rate:rate,end_date:end,start_date:st,annual_interest:ai},function(err){if(err)return alert(err.message);m.classList.remove('on');renderShared()})};q('#seDelete').onclick=function(){if(!confirm('„'+(l.name||'Kredit')+'“ wirklich löschen?'))return;api('delete_loan',{loan_id:id},function(err){if(err)return alert(err.message);m.classList.remove('on');renderShared()})}}
function openSharedSpecial(id){var m=sharedModal('Gemeinsame Sonderzahlung','<div class="field"><label>Betrag (€)</label><input id="ssAmt" type="number" step="0.01"></div><div class="field"><label>Datum</label><input id="ssDate" type="date"></div><div class="field"><label>Notiz (optional)</label><input id="ssNote"></div><button class="btn primary" id="ssSave" style="width:100%">Eintragen</button>');q('#ssDate').value=today();q('#ssSave').onclick=function(){var a=money(q('#ssAmt').value);if(!a)return alert('Bitte Betrag eingeben.');api('special',{loan_id:id,amount:a,booking_date:q('#ssDate').value||today(),note:q('#ssNote').value.trim()||'Sonderzahlung'},function(err){if(err)return alert(err.message);m.classList.remove('on');renderShared()})}}
function openSharedHistory(id){var h=[],i,x;for(i=0;i<sharedTx.length;i++)if(String(sharedTx[i].loan_id)===String(id))h.push(sharedTx[i]);h.sort(function(a,b){return String(b.booking_date||'').localeCompare(String(a.booking_date||''))});var html=h.length?'':'<div class="empty">Noch keine Buchungen.</div>';for(i=0;i<h.length;i++){x=h[i];html+='<div style="display:flex;justify-content:space-between;gap:10px;padding:10px 0;border-bottom:1px solid var(--l)"><span>'+(x.type==='rate'?'Monatsrate':'Sonderzahlung')+'<br><small class="muted">'+fmt(x.booking_date)+' · '+(x.note||'')+'</small></span><strong>− '+euro(x.amount)+'</strong></div>'}sharedModal('Gemeinsamer Verlauf',html)}
function renderSharedCards(root,j){sharedLoans=j.loans||[];sharedTx=j.transactions||[];var html='<div class="card"><div class="head"><div><h2>'+(j.space&&j.space.name?j.space.name:'Gemeinsam')+'</h2><div class="muted">Synchronisierung aktiv</div></div></div></div>',k,l,o,b,done,p,fin,hc;if(!sharedLoans.length)html+='<div class="empty">Noch kein gemeinsamer Kredit.</div>';for(k=0;k<sharedLoans.length;k++){l=sharedLoans[k];o=Math.max(money(l.original),money(l.balance),0.01);b=money(l.balance);done=Math.max(0,o-b);p=Math.min(100,Math.max(0,done/o*100));fin=projected(b,l.rate,l.next_due);hc=0;for(var t=0;t<sharedTx.length;t++)if(String(sharedTx[t].loan_id)===String(l.id))hc++;html+='<div class="loan sharedV30" data-shared-id="'+l.id+'"><div class="loanTop"><div><h3>'+(l.name||'Kredit')+'</h3><div class="loanMeta">Rate '+euro(l.rate)+' · nächste '+fmt(l.next_due)+' · fertig ca. '+(b?fmt(fin):'Abbezahlt')+'</div></div><strong>'+euro(b)+'</strong></div><div class="loanProgress"><div class="progress"><i style="width:'+p+'%"></i></div><div class="loanProgressText"><span>'+Math.round(p)+' % getilgt</span><span>'+euro(done)+' geschafft</span></div></div><details class="loanMore"><summary>Aktionen anzeigen</summary><div class="loanBtns"><button data-sh-edit>Bearbeiten</button><button data-sh-special>+ Sonderzahlung</button><button data-sh-history>Verlauf ('+hc+')</button></div></details></div>'}root.innerHTML=html;root.onclick=function(e){var t=e.target,card=t;while(card&&card!==root&&!(card.classList&&card.classList.contains('sharedV30')))card=card.parentNode;if(!card||card===root)return;var id=card.getAttribute('data-shared-id');if(t.hasAttribute('data-sh-edit'))openSharedEdit(id);else if(t.hasAttribute('data-sh-special'))openSharedSpecial(id);else if(t.hasAttribute('data-sh-history'))openSharedHistory(id)}}
function renderShared(){var root=q('#sharedRoot');if(!root)return;var code=localStorage.getItem(SHARED_KEY)||'';if(!code){root.innerHTML='<div class="card"><h2>Gemeinsam</h2><p class="muted">Noch keine gemeinsame Verbindung eingerichtet.</p></div>';return}root.innerHTML='<div class="card">Gemeinsame Daten werden geladen …</div>';api('list',{},function(err,j){if(err){root.innerHTML='<div class="card"><h2>Gemeinsam</h2><p class="muted">Verbindung konnte nicht geladen werden.</p></div>';return}renderSharedCards(root,j)})}
function bind(){ensurePrivateStartAmount();var tabs=qa('.tab'),i;for(i=0;i<tabs.length;i++){tabs[i].onclick=function(e){if(e)e.preventDefault();showPage(this.getAttribute('data-page'),this);return false}}var adds=qa('[data-action="add"]');for(i=0;i<adds.length;i++){adds[i].onclick=function(e){if(e)e.preventDefault();openLoan('');return false}}var backs=qa('[data-action="backup"]');for(i=0;i<backs.length;i++){backs[i].onclick=function(e){if(e)e.preventDefault();openBackup();return false}}var closes=qa('[data-close]');for(i=0;i<closes.length;i++){closes[i].onclick=function(e){if(e)e.preventDefault();closeModal(this);return false}}var list=q('#loanList');if(list)list.onclick=function(e){e=e||window.event;var t=e.target||e.srcElement,card=t;while(card&&card!==list&&!(card.classList&&card.classList.contains('loan')))card=card.parentNode;if(!card||card===list)return;var id=card.getAttribute('data-id');if(t.hasAttribute('data-edit'))openLoan(id);else if(t.hasAttribute('data-special')){q('#spId').value=id;q('#spAmt').value='';q('#spDate').value=today();q('#specialModal').classList.add('on')}};var ver=q('.version');if(ver)ver.textContent='Kredit App · v30';document.addEventListener('click',function(e){var t=e.target;if(t&&t.id==='saveLoan'){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();saveLoan()}},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();