(()=>{'use strict';
const PRIVATE_KEY='kreditplaner_v1',SHARED_KEY='kreditplaner_shared_code';
const ENDPOINT='https://ymjngslafotilihvvbbl.supabase.co/functions/v1/couple-sync';
const APIKEY='sb_publishable_dLzM2hTl77RvOIEdc78hRA_5xJAF02r';
const $=s=>document.querySelector(s);
function money(v){const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.round(n*100)/100):0}
function loadPrivate(){try{const x=JSON.parse(localStorage.getItem(PRIVATE_KEY));return x&&Array.isArray(x.loans)?x:{loans:[]}}catch{return{loans:[]}}}
async function sharedApi(action,data={}){const code=localStorage.getItem(SHARED_KEY)||'';const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','apikey':APIKEY},body:JSON.stringify({action,code,...data})});const j=await r.json().catch(()=>({error:'Serverfehler'}));if(!r.ok)throw new Error(j.error||'Fehler');return j}
function addStyle(){if($('#ui-fixes-style'))return;const s=document.createElement('style');s.id='ui-fixes-style';s.textContent='.sharedFieldLabel{display:block;font-size:12px;font-weight:750;color:var(--t);margin:2px 0 5px}.sharedFieldWrap{display:grid;gap:0}.dangerBtn{border:1px solid color-mix(in srgb,var(--d) 45%,var(--l))!important;color:var(--d)!important;background:color-mix(in srgb,var(--c) 94%,var(--d) 6%)!important}.sharedBtns{grid-template-columns:repeat(3,1fr)!important}@media(max-width:430px){.sharedBtns{grid-template-columns:1fr!important}}';document.head.appendChild(s)}
function labelInput(input,text){if(!input||input.closest('.sharedFieldWrap'))return;const wrap=document.createElement('div');wrap.className='sharedFieldWrap';const label=document.createElement('label');label.className='sharedFieldLabel';label.textContent=text;label.htmlFor=input.id;input.parentNode.insertBefore(wrap,input);wrap.appendChild(label);wrap.appendChild(input)}
function labelSharedForm(){const m=$('#sharedModal');if(!m?.classList.contains('on'))return;const title=$('#sharedModalTitle')?.textContent||'';if(title.includes('Kredit anlegen')||title.includes('Kredit bearbeiten')){labelInput($('#shName'),'Name');labelInput($('#shRate'),'Monatsrate (€)');labelInput($('#shEnd'),'Enddatum');labelInput($('#shStart'),'Startdatum (optional)');labelInput($('#shInterest'),'Jahreszins % (optional)')}else if(title.includes('Sonderzahlung')){labelInput($('#shSpAmt'),'Betrag (€)');labelInput($('#shSpDate'),'Datum');labelInput($('#shSpNote'),'Notiz (optional)')}}
function privateDeleteButton(){const modal=$('#loanModal');if(!modal)return;let btn=$('#deletePrivateEdit');const id=$('#loanId')?.value||'';if(!id){btn?.remove();return}if(!btn){btn=document.createElement('button');btn.id='deletePrivateEdit';btn.className='btn dangerBtn';btn.textContent='Kredit löschen';const buttons=modal.querySelector('.modalBtns');buttons?.after(btn);btn.style.width='100%';btn.style.marginTop='10px'}btn.onclick=()=>{const state=loadPrivate(),loan=state.loans.find(l=>l.id===($('#loanId')?.value||''));if(!loan)return;if(!confirm(`„${loan.name}“ wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.`))return;state.loans=state.loans.filter(l=>l.id!==loan.id);localStorage.setItem(PRIVATE_KEY,JSON.stringify(state));location.reload()}}
function observePrivate(){const modal=$('#loanModal');if(!modal)return;new MutationObserver(()=>{if(modal.classList.contains('on'))setTimeout(privateDeleteButton,0)}).observe(modal,{attributes:true,attributeFilter:['class']})}
function decorateSharedCards(){document.querySelectorAll('#sharedLoans .sharedLoan').forEach(card=>{if(card.querySelector('.editShared'))return;const row=card.querySelector('.sharedBtns');if(!row)return;const b=document.createElement('button');b.className='editShared';b.textContent='Bearbeiten';row.appendChild(b);b.onclick=e=>{e.stopPropagation();openSharedEdit(card.dataset.id)}})}
async function openSharedEdit(id){try{const j=await sharedApi('list'),loan=(j.loans||[]).find(x=>x.id===id);if(!loan)return alert('Kredit nicht gefunden.');let m=$('#sharedModal');if(!m){m=document.createElement('div');m.id='sharedModal';m.className='modal';m.innerHTML='<div class="sheet"><h3 id="sharedModalTitle"></h3><div id="sharedModalBody"></div><div class="modalBtns"><button class="btn" id="closeSharedModal">Schließen</button></div></div>';document.body.appendChild(m);$('#closeSharedModal').onclick=()=>m.classList.remove('on')}$('#sharedModalTitle').textContent='Gemeinsamen Kredit bearbeiten';$('#sharedModalBody').innerHTML='<div class="sharedForm"><input id="shName"><input id="shRate" type="number" step="0.01" inputmode="decimal"><input id="shEnd" type="date"><input id="shStart" type="date"><input id="shInterest" type="number" min="0" step="0.01" inputmode="decimal"><button class="btn primary" id="saveSharedEdit">Änderungen speichern</button><button class="btn dangerBtn" id="deleteSharedEdit">Kredit löschen</button></div>';$('#shName').value=loan.name||'';$('#shRate').value=loan.rate??'';$('#shEnd').value=loan.end_date||'';$('#shStart').value=loan.start_date||'';$('#shInterest').value=loan.annual_interest??'';m.classList.add('on');labelSharedForm();$('#saveSharedEdit').onclick=async()=>{const name=$('#shName').value.trim(),rate=money($('#shRate').value),end_date=$('#shEnd').value,start_date=$('#shStart').value||null,iv=$('#shInterest').value,annual_interest=iv===''?null:Number(iv);if(!name||!rate||!end_date)return alert('Bitte Name, Monatsrate und Enddatum ausfüllen.');try{await sharedApi('update_loan',{loan_id:id,name,rate,end_date,start_date,annual_interest});m.classList.remove('on');location.reload()}catch(e){alert(e.message)}};$('#deleteSharedEdit').onclick=async()=>{if(!confirm(`„${loan.name}“ wirklich löschen? Auch der gemeinsame Verlauf dieses Kredits wird gelöscht.`))return;try{await sharedApi('delete_loan',{loan_id:id});m.classList.remove('on');location.reload()}catch(e){alert(e.message)}}}catch(e){alert(e.message)}}
function start(){addStyle();observePrivate();const bodyObs=new MutationObserver(()=>{labelSharedForm();decorateSharedCards()});bodyObs.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});setInterval(decorateSharedCards,1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();