(function(){'use strict';
var KEY='kreditplaner_v1',SHARED_KEY='kreditplaner_shared_code',ENDPOINT='https://ymjngslafotilihvvbbl.supabase.co/functions/v1/couple-sync',APIKEY='sb_publishable_dLzM2hTl77RvOIEdc78hRA_5xJAF02r',shared=[],tx=[];
function q(s){return document.querySelector(s)}function money(v){var n=Number(v)||0;return Math.max(0,Math.round(n*100)/100)}function euro(v){return money(v).toLocaleString('de-DE',{style:'currency',currency:'EUR'})}function code(){return localStorage.getItem(SHARED_KEY)||''}function parse(s){if(!s)return null;var p=s.split('-');return p.length===3?new Date(Date.UTC(+p[0],+p[1]-1,+p[2])):null}function fmt(s){var d=parse(s);return d?new Intl.DateTimeFormat('de-DE').format(d):'—'}function addM(s,n){var d=parse(s);if(!d)return null;var day=d.getUTCDate(),t=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+n,1)),last=new Date(Date.UTC(t.getUTCFullYear(),t.getUTCMonth()+1,0)).getUTCDate();t.setUTCDate(Math.min(day,last));return t.toISOString().slice(0,10)}function nextFirst(){var d=new Date();return new Date(d.getFullYear(),d.getMonth()+1,1).toISOString().slice(0,10)}function installments(a,b){var x=parse(a),y=parse(b);if(!x||!y)return 0;var n=(y.getUTCFullYear()-x.getUTCFullYear())*12+y.getUTCMonth()-x.getUTCMonth();return n<0?0:n+1}function api(action,data,cb){if(!code())return cb(new Error('Bitte zuerst unter Einstellungen gemeinsam verbinden.'));var x=new XMLHttpRequest(),body={action:action,code:code()},k;for(k in data||{})body[k]=data[k];x.open('POST',ENDPOINT,true);x.setRequestHeader('Content-Type','application/json');x.setRequestHeader('apikey',APIKEY);x.onreadystatechange=function(){if(x.readyState!==4)return;var j={};try{j=JSON.parse(x.responseText||'{}')}catch(e){}if(x.status<200||x.status>=300)return cb(new Error(j.error||'Verbindung fehlgeschlagen'));cb(null,j)};x.send(JSON.stringify(body))}
function state(){try{var s=JSON.parse(localStorage.getItem(KEY)||'{"loans":[]}');return s&&Array.isArray(s.loans)?s:{loans:[]}}catch(e){return{loans:[]}}}function saveState(s){localStorage.setItem(KEY,JSON.stringify(s))}
function ensureForm(){var modal=q('#loanModal');if(!modal||q('#loanScope'))return;var details=modal.querySelector('details'),f=document.createElement('div');f.className='field';f.innerHTML='<label>Bereich</label><select id="loanScope" style="width:100%;min-height:47px;border:1px solid var(--l);border-radius:13px;padding:9px 11px;background:var(--b);color:var(--t);font-size:16px"><option value="private">Alleine</option><option value="shared">Gemeinsam</option></select><input id="loanOrigin" type="hidden">';modal.querySelector('.sheet').insertBefore(f,details);}
function setupNav(){var old=q('.tab[data-page="shared"]');if(old)old.style.display='none';var page=q('#shared');if(page)page.style.display='none';var nav=q('.nav');if(nav)nav.style.gridTemplateColumns='repeat(2,1fr)';var top=q('#finanzAppSwitch');if(top&&!q('#settingsLink')){top.style.gridTemplateColumns='repeat(3,1fr)';var a=document.createElement('a');a.id='settingsLink';a.href='einstellungen.html';a.textContent='⚙️ Einstellungen';top.appendChild(a)}}
function loadShared(){if(!code()){shared=[];tx=[];appendShared();return}api('list',{},function(err,j){if(err)return;shared=j.loans||[];tx=j.transactions||[];appendShared()})}
function appendShared(){var box=q('#loanList');if(!box)return;var olds=box.querySelectorAll('.unifiedShared'),i;for(i=0;i<olds.length;i++)olds[i].remove();if(!shared.length)return;var empty=box.querySelector('.empty');if(empty&&state().loans.length===0)empty.remove();for(i=0;i<shared.length;i++){var l=shared[i],o=Math.max(money(l.original),money(l.balance),.01),b=money(l.balance),done=Math.max(0,o-b),pct=Math.min(100,done/o*100),fin=b&&l.rate?addM(l.next_due,Math.max(0,Math.ceil(b/money(l.rate))-1)):null,h=0,t;for(t=0;t<tx.length;t++)if(String(tx[t].loan_id)===String(l.id))h++;var d=document.createElement('div');d.className='loan unifiedShared';d.setAttribute('data-shared-id',l.id);d.innerHTML='<div class="loanTop"><div><h3>'+esc(l.name||'Kredit')+'</h3><div class="loanMeta"><span style="color:#a7f3d0;font-weight:800">↻ Gemeinsam</span> · Rate '+euro(l.rate)+' · nächste '+fmt(l.next_due)+' · fertig ca. '+(fin?fmt(fin):'Abbezahlt')+'</div></div><strong>'+euro(b)+'</strong></div><div class="loanProgress"><div class="progress"><i style="width:'+pct+'%"></i></div><div class="loanProgressText"><span>'+Math.round(pct)+' % getilgt</span><span>'+euro(done)+' geschafft</span></div></div><details class="loanMore"><summary>Aktionen anzeigen</summary><div class="loanBtns"><button data-us-edit>Bearbeiten</button><button data-us-special>+ Sonderzahlung</button><button data-us-history>Verlauf ('+h+')</button></div></details>';box.appendChild(d)}}function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function openShared(l){ensureForm();q('#loanId').value=l.id;q('#loanOrigin').value='shared';q('#loanScope').value='shared';q('#loanTitle').textContent='Kredit bearbeiten';q('#name').value=l.name||'';q('#rate').value=l.rate||'';q('#end').value=l.end_date||'';q('#start').value=l.start_date||'';q('#interest').value=l.annual_interest==null?'':l.annual_interest;if(q('#startAmount'))q('#startAmount').value=l.original||'';q('#deleteLoan').style.display='block';q('#loanModal').classList.add('on')}
function resetNewScope(){ensureForm();setTimeout(function(){if(!q('#loanId').value){q('#loanOrigin').value='';q('#loanScope').value='private'}else if(!q('#loanOrigin').value){q('#loanScope').value='private'}},0)}
function createShared(p,cb){api('create_loan',p,cb)}
function privateDelete(id){var s=state();s.loans=s.loans.filter(function(x){return String(x.id)!==String(id)});saveState(s)}
function privateCreate(p){var s=state(),id=String(Date.now())+String(Math.random()).slice(2,7);s.loans.push({id:id,name:p.name,original:p.original,balance:p.balance,rate:p.rate,nextDue:p.next_due,endDate:p.end_date,startDate:p.start_date||'',annualInterest:p.annual_interest,history:[]});saveState(s)}
function payload(){var rate=money(q('#rate').value),end=q('#end').value,due=nextFirst(),n=installments(due,end),entered=money(q('#startAmount')?q('#startAmount').value:0),sum=money(rate*n);return{name:q('#name').value.trim()||'Kredit',rate:rate,end_date:end,start_date:q('#start').value||null,annual_interest:q('#interest').value===''?null:Number(q('#interest').value),original:entered>0?Math.max(entered,sum):sum,balance:sum,next_due:due}}
function special(id){var a=prompt('Betrag der Sonderzahlung (€):');a=money(a);if(!a)return;api('special',{loan_id:id,amount:a,booking_date:new Date().toISOString().slice(0,10),note:'Sonderzahlung'},function(err){if(err)return alert(err.message);loadShared()})}
function history(id){var h=tx.filter(function(x){return String(x.loan_id)===String(id)}).sort(function(a,b){return String(b.booking_date).localeCompare(String(a.booking_date))}),s='';for(var i=0;i<h.length;i++)s+=fmt(h[i].booking_date)+' · '+(h[i].type==='rate'?'Monatsrate':'Sonderzahlung')+' · '+euro(h[i].amount)+'\n';alert(s||'Noch keine Buchungen.')}
function init(){ensureForm();setupNav();setTimeout(setupNav,300);setTimeout(loadShared,350);document.addEventListener('click',function(e){var add=e.target.closest('[data-action="add"]');if(add)resetNewScope();var card=e.target.closest('.unifiedShared');if(card){var id=card.getAttribute('data-shared-id'),l=shared.filter(function(x){return String(x.id)===String(id)})[0];if(e.target.hasAttribute('data-us-edit')){e.preventDefault();e.stopImmediatePropagation();openShared(l)}else if(e.target.hasAttribute('data-us-special')){e.preventDefault();e.stopImmediatePropagation();special(id)}else if(e.target.hasAttribute('data-us-history')){e.preventDefault();e.stopImmediatePropagation();history(id)}return}if(e.target.id==='saveLoan'){ensureForm();var origin=q('#loanOrigin').value,target=q('#loanScope').value;if(origin!=='shared'&&target!=='shared')return;e.preventDefault();e.stopImmediatePropagation();var p=payload(),id=q('#loanId').value;if(!p.rate||!p.end_date||!p.original)return alert('Bitte Monatsrate und Enddatum ausfüllen.');if(target==='shared'&&!code())return alert('Bitte zuerst unter Einstellungen gemeinsam verbinden.');if(origin==='shared'&&target==='shared'){api('update_loan',{loan_id:id,name:p.name,rate:p.rate,end_date:p.end_date,start_date:p.start_date,annual_interest:p.annual_interest},function(err){if(err)return alert(err.message);q('#loanModal').classList.remove('on');loadShared()})}else if(origin==='shared'&&target==='private'){privateCreate(p);api('delete_loan',{loan_id:id},function(err){if(err)return alert(err.message);location.reload()})}else{createShared(p,function(err){if(err)return alert(err.message);if(id)privateDelete(id);q('#loanModal').classList.remove('on');location.reload()})}},true);document.addEventListener('click',function(e){if(e.target.id==='deleteLoan'&&q('#loanOrigin')&&q('#loanOrigin').value==='shared'){e.preventDefault();e.stopImmediatePropagation();var id=q('#loanId').value;if(!confirm('Kredit wirklich löschen?'))return;api('delete_loan',{loan_id:id},function(err){if(err)return alert(err.message);q('#loanModal').classList.remove('on');loadShared()})}},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();